Repository googleapis/python-bigquery-connection, pull requests merged in 2021-01, with the labels that each got.

#36 chore: add pre-commit
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  noxfile.py
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: partial

#37 fix: remove gRPC send/recv limits
  google/cloud/bigquery_connection_v1/services/connection_service/transports/__init__.py
  google/cloud/bigquery_connection_v1/services/connection_service/transports/grpc.py
  google/cloud/bigquery_connection_v1/services/connection_service/transports/grpc_asyncio.py
  google/cloud/bigquery_connection_v1/types/__init__.py
  synth.metadata
  tests/unit/gapic/bigquery_connection_v1/test_connection_service.py
Labels: api: bigqueryconnection, automerge, cla: yes, context: partial

#39 chore: add constraints file
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
Labels: api: bigqueryconnection, cla: yes
