Repository googleapis/python-bigquery-connection, pull requests merged in 2021-04, with the labels that each got.

#56 test(python): use constraints files to check dependency lower bounds
  .pre-commit-config.yaml
  noxfile.py
  setup.py
  synth.metadata
  synth.py
  testing/constraints-3.6.txt
Labels: api: bigqueryconnection, cla: yes, context: partial

#59 chore: prevent normalization of semver versioning
  setup.py
Labels: api: bigqueryconnection, cla: yes

#61 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  noxfile.py
  owlbot.py
  synth.metadata
Labels: api: bigqueryconnection, cla: yes

#60 chore: use workaround for sic
  setup.py
Labels: api: bigqueryconnection, cla: yes

#62 chore(revert): Revert "chore: use workaround for sic (#60)"
  setup.py
Labels: api: bigqueryconnection, automerge, cla: yes

#64 chore: add yoshi to CODEOWNERS
  .github/CODEOWNERS
Labels: api: bigqueryconnection, cla: yes
